backend:
  name: github
  repo: zotim4git/tripwithme    # 깃허브 user/repo
  branch: main
  base_url: https://tripwithme-nine.vercel.app
  auth_endpoint: api/auth

media_folder: "src/uploads"
public_folder: "/uploads"

collections:
  - name: "seoul"
    label: "Seoul"
    folder: "src/seoul_spot"
    create: true

    # 파일명 규칙 → slug 필드 값으로 파일 생성
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug (URL)"
        name: "slug"
        widget: "slug"
        from: "title"
        hint: "영어소문자-숫자-하이픈만 (예: seoul-sungbuk)"

      - label: "City"
        name: "city"
        widget: "hidden"
        default: "seoul"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Main Image"
        name: "main_image"
        widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
        